# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'postagem', 'verbose_name_plural': 'postagens'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque está opção apenas quando o post estiver pronto para ser visualizado pelo público!', verbose_name='publicado?'),
        ),
    ]
