# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170603_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='', verbose_name='meta descrição'),
            preserve_default=False,
        ),
    ]
