# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 17:45
from __future__ import unicode_literals

from django.db import migrations
import girox.blog.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=girox.blog.models.post_directory_path, verbose_name='foto de capa'),
        ),
    ]
