# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170620_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateField(db_index=True, verbose_name='data'),
        ),
    ]
