# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import girox.advertising.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('link', models.CharField(max_length=250)),
                ('banner', versatileimagefield.fields.VersatileImageField(help_text='Imagem com: 300 X 250 pixels', upload_to=girox.advertising.models.advertiser_directory_path, verbose_name='arquivo')),
                ('order', models.IntegerField(unique=True, verbose_name='ordem')),
                ('is_public', models.BooleanField(default=False, verbose_name='é pública?')),
                ('expiration_date', models.DateField(verbose_name='data de validade')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observação')),
            ],
            options={
                'verbose_name_plural': 'anunciantes',
                'verbose_name': 'anunciante',
            },
        ),
    ]
