# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'ordering': ('order',), 'verbose_name': 'anunciante', 'verbose_name_plural': 'anunciantes'},
        ),
    ]
