# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import girox.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170415_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=girox.gallery.models.album_directory_path, verbose_name='arquivo'),
        ),
    ]
