# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170419_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('album', 'file'), 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
    ]
