# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:03
from __future__ import unicode_literals

from django.db import migrations
import girox.gallery.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170420_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to=girox.gallery.models.album_directory_path, verbose_name='arquivo'),
        ),
    ]
