# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170424_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-date_added', '-order')},
        ),
    ]
