# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='event',
        ),
    ]
