# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_subscription_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
            preserve_default=False,
        ),
    ]
