# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170329_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='data_limite_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data limite de inscrição'),
            preserve_default=False,
        ),
    ]
