# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170330_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='data_limite_inscricao',
            new_name='date_limit_subscription',
        ),
    ]
