# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170330_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='data do evento'),
        ),
    ]
