# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import girox.event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20170331_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.CharField(default='end', max_length=255, verbose_name='endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(default='00000000000', help_text='apenas dígitos. (Informação necessária para o seguro)', max_length=11, validators=[girox.event.validators.validate_cpf], verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data nascimento'),
            preserve_default=False,
        ),
    ]
