# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20170406_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsorsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/sponsors/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='event.Event')),
            ],
        ),
    ]
