# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventsponsorsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsponsorsimage',
            options={'verbose_name': 'patrocinador', 'verbose_name_plural': 'patrocinadores'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='eventsponsorsimage',
            name='image',
            field=models.ImageField(upload_to='events/sponsors/', verbose_name='imagem'),
        ),
    ]
