# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20170408_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='equipe'),
        ),
    ]
