# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0016_subscription_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='organizadores'),
        ),
    ]
