# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_organizers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'inscrições',
                'verbose_name': 'inscrição',
                'proxy': True,
            },
            bases=('event.subscription',),
        ),
    ]
