# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_subscriptionproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionproxy',
            options={'verbose_name': 'participante', 'verbose_name_plural': 'participantes'},
        ),
    ]
