# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_resumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='resumo',
            new_name='resume',
        ),
    ]
