# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20170426_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_limit_subscription',
            field=models.PositiveIntegerField(default=0, help_text='Zero para quantidade ilimitada!', verbose_name='quantidade limite de inscrições'),
        ),
    ]
