# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_number_limit_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
    ]
